BUILD_DIR=build
PROGNAME_TARG=progname

include config.mk
SRCS = main.c
OBJS = $(patsubst %,$(BUILD_DIR)/%.o,$(SRCS))
DEPS = $(OBJS:.o=.d)
-include $(DEPS)

build/$(PROGNAME_TARG): $(OBJS)
	@mkdir -p $(@D)
	$(CC) -o $@ $(CFLAGS) $(CPPFLAGS) $^ $(LIBS)

$(BUILD_DIR)/%.c.o: src/%.c
	@mkdir -p $(@D)
	$(CC) -c -o $@ -MMD $(CFLAGS) $(CPPFLAGS) $<

clean:
	rm -rf $(BUILD_DIR)

.PHONY: clean
